version: 2
updates:

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: "develop"
  open-pull-requests-limit: 5

  labels:
  - "dependencies"
  - "npm"
  - "automated-update"

  groups:
    app-dependencies:
      patterns:
      - "*"
      exclude-patterns:
      - "major"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "develop"

  labels:
  - "dependencies"
  - "github-actions"
  - "automated-update"

  groups:
    actions-updates:
      patterns:
      - "*"
